name: First-WorkFlow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Class
        run: echo "My name is Mikey"
      - name : Checkout
        uses: actions/checkout@v4
      - name: list files
        run: ls -la
      - name: Read file
        run: cat README.md
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repo
        uses: actions/checkout@v4
      - name: Run Command
        run: |
          echo "Hello"
          echo "My name is Mikey"
          ls -la
          cat README.md

  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cowsay -y
      - name: Run Command
        run: |
          cowsay "Hello Wold My name is Mikey" >> Mikey.txt
      - name: Test File
        run: grep "Mikey" Mikey.txt
      - name: Read File
        run: cat Mikey.txt
      - name: list
        run: ls

