name: First-WorkFlow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Class
        run: echo "My name is Mikey"
      - name : Checkout
        uses: actions/checkout@v4
      - name: list files
        run: ls -la
      - name: Read file
        run: cat README.md
