name: test

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run Command
              run: |
                  echo "Hello"
                  echo "My name is Mikey"
                  ls -la
                  cat README.md
